build:
  stage: build
  tags:
    - shell
    - paleosrv3
  script:
    - echo "This is the build stage"
    - echo "It will create a NGINX container which monitoring sites can connect to"
    - echo "The following command will be run:"
    - echo "docker rm -f monitoring-base || true"
    - docker rm -f monitoring-base || true
    - echo "docker run -it --rm -d -p 8080:80 --name monitoring-base nginx"
    - docker run -it --rm -d -p 8080:80 --name monitoring-base -v "$(pwd)"/site-content:/usr/share/nginx/html nginx
